# Generated by Django 5.2.7 on 2025-12-26 01:33

import apps.products.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=apps.products.models.product_image_upload_path,
            ),
        ),
    ]
