# Generated by Django 5.2.7 on 2026-01-07 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_orderproduct_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="total_price",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_products",
                to="orders.order",
            ),
        ),
    ]
