# Generated by Django 5.2.7 on 2026-01-07 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_orderproduct_total_price_orderproduct_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
