# Generated by Django 5.2.7 on 2025-12-30 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-created_at"]},
        ),
    ]
