# Generated by Django 5.2.7 on 2025-12-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cart_created_by_alter_cartproduct_cart_and_more"),
        ("products", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
