# Generated by Django 5.2.7 on 2025-12-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cartproduct_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartproduct",
            old_name="product",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
            ),
        ),
    ]
