# Generated by Django 5.2.7 on 2025-12-30 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_rename_product_cartproduct_product_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartproduct",
            old_name="product_id",
            new_name="product",
        ),
    ]
