# Generated by Django 5.2.7 on 2025-12-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_rename_product_id_cartproduct_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="cart.cart",
            ),
        ),
    ]
