# Generated by Django 5.2.7 on 2026-01-07 04:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_alter_cart_created_by"),
        ("products", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartproduct",
            unique_together={("cart", "product")},
        ),
    ]
