# Generated by Django 5.2.7 on 2026-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0014_alter_cart_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
